version: '3.8'

services:
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hangman
    ports:
      - '5432:5432'
    user: postgres
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
    #   interval: 5s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 5s
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    # healthcheck:
    #   test: ['CMD', 'redis-cli', 'ping']
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s